name: "Docs Update Request"
description: Create an update request for Zeytal’s documentation
title: "[docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        > Thanks for helping us improve zeytal. Before submitting, search for open/closed issues as the issue may have already been reported/addressed.

  - type: markdown
    attributes:
      value: |
        If you aren't sure this should be opened as an issue, [open a discussion instead](https://github.com/provok-exe/zeytal/discussions).

  - type: textarea
    id: update-description
    attributes:
      label: Update description
      description: Tell us about your update request
      placeholder: "I think this update would be great because..."
      value: "Describe your update request..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the update request here.
      placeholder: ex. screenshots, Stack Overflow links, forum links, etc.
      value: "Additional details here..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/provok-exe/zeytal/blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues and PRs
          required: true
